require:
  - rubocop-packaging

AllCops:
  NewCops: enable
  Exclude:
    - bundle/vendors/**/*
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 170

Lint/UselessComparison:
  Enabled: false

Metrics/ClassLength:
  Max: 165

Metrics/MethodLength:
  Max: 24

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
