require:
  - rubocop-packaging

AllCops:
  Exclude:
    - bundle/vendors/**/*

Documentation:
  Enabled: false

Lint/UselessComparison:
  Enabled: false

Metrics/ClassLength:
  Max: 165

# Work in progress
Metrics/LineLength:
  Max: 183

# Work in progress
Metrics/MethodLength:
  Max: 24

# Work in progress
Metrics/PerceivedComplexity:
  Max: 8

Style/NumericLiterals:
  MinDigits: 10

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
