version: 2
jobs:
  build:
    working_directory: ~/iso8601
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          TESTOPTS: "--ci-dir=/tmp/test-results"
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: iso8601-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: iso8601-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Run minitest
      - type: shell
        command: bundle exec rspec

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
